CLASS LHC_ZSALESORDERITEM DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      UPDATE FOR MODIFY
        IMPORTING
          ENTITIES FOR UPDATE  ZSalesOrderItem,
      DELETE FOR MODIFY
        IMPORTING
          KEYS FOR DELETE  ZSalesOrderItem,
      READ FOR READ
        IMPORTING
          KEYS FOR READ  ZSalesOrderItem
        RESULT result,
      RBA_ZSALESORDERHEADER FOR READ
        IMPORTING
          KEYS_RBA FOR READ  ZSalesOrderItem\_ZSalesOrderHeader
        FULL result_requested
        RESULT result
        LINK association_links.
ENDCLASS.

CLASS LHC_ZSALESORDERITEM IMPLEMENTATION.
  METHOD UPDATE.
  ENDMETHOD.
  METHOD DELETE.
  ENDMETHOD.
  METHOD READ.
  ENDMETHOD.
  METHOD RBA_ZSALESORDERHEADER.
  ENDMETHOD.
ENDCLASS.
