CLASS LHC_ZSALESORDERHEADER DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZSalesOrderHeader
        RESULT result,
      CREATE FOR MODIFY
        IMPORTING
          ENTITIES FOR CREATE  ZSalesOrderHeader,
      UPDATE FOR MODIFY
        IMPORTING
          ENTITIES FOR UPDATE  ZSalesOrderHeader,
      DELETE FOR MODIFY
        IMPORTING
          KEYS FOR DELETE  ZSalesOrderHeader,
      LOCK FOR LOCK
        IMPORTING
          KEYS FOR LOCK  ZSalesOrderHeader,
      READ FOR READ
        IMPORTING
          KEYS FOR READ  ZSalesOrderHeader
        RESULT result,
      CBA_ZSALESORDERITEM FOR MODIFY
        IMPORTING
          ENTITIES_CBA FOR CREATE  ZSalesOrderHeader\_ZSalesOrderItem,
      RBA_ZSALESORDERITEM FOR READ
        IMPORTING
          KEYS_RBA FOR READ  ZSalesOrderHeader\_ZSalesOrderItem
        FULL result_requested
        RESULT result
        LINK association_links.
ENDCLASS.

CLASS LHC_ZSALESORDERHEADER IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
  METHOD CREATE.


   Return.

  ENDMETHOD.
  METHOD UPDATE.
  ENDMETHOD.
  METHOD DELETE.
  ENDMETHOD.
  METHOD LOCK.
  ENDMETHOD.
  METHOD READ.
  ENDMETHOD.
  METHOD CBA_ZSALESORDERITEM.
  ENDMETHOD.
  METHOD RBA_ZSALESORDERITEM.
  ENDMETHOD.
ENDCLASS.
CLASS LCL_ZR_ZSALESORDERHEADER01TP DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_SAVER.
  PROTECTED SECTION.
    METHODS:
      FINALIZE REDEFINITION,
      CHECK_BEFORE_SAVE REDEFINITION,
      SAVE REDEFINITION,
      CLEANUP REDEFINITION,
      CLEANUP_FINALIZE REDEFINITION.
ENDCLASS.

CLASS LCL_ZR_ZSALESORDERHEADER01TP IMPLEMENTATION.
  METHOD FINALIZE.
  ENDMETHOD.
  METHOD CHECK_BEFORE_SAVE.
  ENDMETHOD.
  METHOD SAVE.
  ENDMETHOD.
  METHOD CLEANUP.
  ENDMETHOD.
  METHOD CLEANUP_FINALIZE.
  ENDMETHOD.
ENDCLASS.
